### ISSUE TITLE
public archiving

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/McGregor_climate-sensitivity-variation#86]
Current text:

"All data, code, and results are available through the SCBI-ForestGEO organization on GitHub (https://github.com/SCBI-ForestGEO: SCBI-ForestGEO-Data and McGregor_climate-sensitivity-variation repositories), with static versions corresponding to data and analyses presented here archived in Zenodo (DOIs: 10.5281/zenodo.3604993 and [TBD], respectively "

Thus, upon acceptance, we need to:

(1) make this repo public
(2) archive in Zenodo

@mcgregorian1, nothing to do with Zenodo before the first submission. 

Do you want to make this whole repo public, or just archive in Zenodo?

**Comment by teixeirak** [comment]
Okay, repo is public!

**Comment by teixeirak** [comment]
Okay, it's released, and on Zenodo: https://zenodo.org/record/4070060#.X30QaR17nzI. 

This is a pre-release; we'll do final release once all files are finalized.

**Comment by mcgregorian1** [comment]
Ok! Thank you

**Comment by mcgregorian1** [comment]
> > [ ] [PDSI data](https://github.com/SCBI-ForestGEO/McGregor_climate-sensitivity-variation/tree/master/non_publication/data/pdsi) for winchester, along with a short script for parsing through it.
> 
> Wouldn't hurt to add this to the ForestGEO climate data repo ([here](https://github.com/forestgeo/Climate/tree/master/Climate_Data/Met_Stations/SCBI), with appropriate README.). But okay to just remove if you don't have time for that.

I'm wasn't able to get to this tonight. The data in there was other exploratory data that I realized the readme didn't cover. I think the main explainers of it are hidden in an early github issue for this repo.

**Comment by teixeirak** [comment]
Don't worry about the PDSI data if it's too complicated.
